# Generated by Django 3.0.2 on 2021-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2085)),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
